#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16.1-alpine3.13

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - node -v
          - npm install
    - step:
        name: Deploy to Dev
        deployment: test
        #trigger: manual
        caches:
          - docker
        services:
          - docker
        script:
          - echo ${DEV_DOCKER_PASSWORD} | docker login "$DEV_DOCKER_REGISTRY" --username "$DEV_DOCKER_USERNAME" --password-stdin
          - docker build . -t pes-frontend:$BITBUCKET_BUILD_NUMBER
          - docker image tag pes-frontend:$BITBUCKET_BUILD_NUMBER $DEV_DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
          - docker image push $DEV_DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
          - pipe: docker://thlim78/azure-web-apps-containers-deploy:1.0.2
            variables:
              AZURE_APP_ID: $DEV_AZURE_APP_ID
              AZURE_PASSWORD: $DEV_AZURE_PASSWORD
              AZURE_TENANT_ID: $DEV_AZURE_TENANT_ID
              AZURE_RESOURCE_GROUP: $DEV_AZURE_RESOURCE_GROUP
              AZURE_APP_NAME: $DEV_AZURE_APP_NAME
              DOCKER_CUSTOM_IMAGE_NAME: $DEV_DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
              DOCKER_REGISTRY_SERVER_URL: $DEV_DOCKER_REGISTRY_SERVER_URL
              DOCKER_REGISTRY_SERVER_USER: $DEV_DOCKER_USERNAME
              DOCKER_REGISTRY_SERVER_PASSWORD: $DEV_DOCKER_PASSWORD
              EXTRA_ARGS: "--settings REACT_APP_BACKEND_URL=$DEV_pes_BACKEND_URL TZ=Australia/Melbourne"
  branches:
    master:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - node -v
            - npm install
      - step:
          name: Deploy to Dev
          deployment: test
          #trigger: manual
          caches:
            - docker
          services:
            - docker
          script:
            - echo ${DEV_DOCKER_PASSWORD} | docker login "$DEV_DOCKER_REGISTRY" --username "$DEV_DOCKER_USERNAME" --password-stdin
            - docker build . -t pes-frontend:$BITBUCKET_BUILD_NUMBER
            - docker image tag pes-frontend:$BITBUCKET_BUILD_NUMBER $DEV_DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
            - docker image push $DEV_DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
            - pipe: docker://thlim78/azure-web-apps-containers-deploy:1.0.2
              variables:
                AZURE_APP_ID: $DEV_AZURE_APP_ID
                AZURE_PASSWORD: $DEV_AZURE_PASSWORD
                AZURE_TENANT_ID: $DEV_AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $DEV_AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $DEV_AZURE_APP_NAME
                DOCKER_CUSTOM_IMAGE_NAME: $DEV_DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
                DOCKER_REGISTRY_SERVER_URL: $DEV_DOCKER_REGISTRY_SERVER_URL
                DOCKER_REGISTRY_SERVER_USER: $DEV_DOCKER_USERNAME
                DOCKER_REGISTRY_SERVER_PASSWORD: $DEV_DOCKER_PASSWORD
                EXTRA_ARGS: "--settings REACT_APP_BACKEND_URL=$DEV_pes_BACKEND_URL TZ=Australia/Melbourne"
      - step:
          name: Deploy to Prod
          deployment: production
          trigger: manual
          caches:
            - docker
          services:
            - docker
          script:
            - echo ${DOCKER_PASSWORD} | docker login "$DOCKER_REGISTRY" --username "$DOCKER_USERNAME" --password-stdin
            - docker build . -t pes-frontend:$BITBUCKET_BUILD_NUMBER
            - docker image tag pes-frontend:$BITBUCKET_BUILD_NUMBER $DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
            - docker image push $DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
            - pipe: docker://thlim78/azure-web-apps-containers-deploy:1.0.2
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $AZURE_APP_NAME
                DOCKER_CUSTOM_IMAGE_NAME: $DOCKER_REGISTRY/pes-frontend:$BITBUCKET_BUILD_NUMBER
                DOCKER_REGISTRY_SERVER_URL: $DOCKER_REGISTRY_SERVER_URL
                DOCKER_REGISTRY_SERVER_USER: $DOCKER_USERNAME
                DOCKER_REGISTRY_SERVER_PASSWORD: $DOCKER_PASSWORD
                EXTRA_ARGS: "--settings REACT_APP_BACKEND_URL=$pes_BACKEND_URL TZ=Australia/Melbourne"
